language: cpp

compiler: gcc

install:
#cpp check
- sudo apt-get install -qq cppcheck
#valgrind
- sudo apt-get install -qq valgrind

script:
- g++ main.cpp -o travis_gcc_cpp98
- ./travis_gcc_cpp98
#cpp check
- cppcheck --quiet --error-exitcode=1 .
#valgrind
- valgrind --leak-check=full -v --show-reachable=yes --log-file=memcheck.log ./travis_gcc_cpp98
- cat memcheck.log
