language: cpp

compiler: gcc

install:
#cpp check
- sudo apt-get install -qq cppcheck

script:
- g++ main.cpp -o travis_gcc_cpp98
- ./travis_gcc_cpp98
#cpp check
- cppcheck --quiet --error-exitcode=1 . 
